-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 18:46:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trueque-libre
-- -----------------------------------------------------
-- Base de datos de la pagina web trueque-libre

-- -----------------------------------------------------
-- Schema trueque-libre
--
-- Base de datos de la pagina web trueque-libre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trueque-libre` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `trueque-libre` ;

-- -----------------------------------------------------
-- Table `trueque-libre`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trueque-libre`.`Users` (
  `id` VARCHAR(50) NOT NULL COMMENT 'GUID generado automaticamente por el backend',
  `userName` VARCHAR(50) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `state` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trueque-libre`.`Publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trueque-libre`.`Publications` (
  `id` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `ubication` VARCHAR(100) NOT NULL,
  `exchange` VARCHAR(255) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `creationUser` VARCHAR(50) NOT NULL,
  `modificationDate` DATETIME NULL,
  `modificationUser` VARCHAR(150) NULL COMMENT 'email del usuario modificador',
  PRIMARY KEY (`id`, `creationUser`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Publications_Users_idx` (`creationUser` ASC),
  CONSTRAINT `fk_Publications_Users`
    FOREIGN KEY (`creationUser`)
    REFERENCES `trueque-libre`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trueque-libre`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trueque-libre`.`Image` (
  `id` VARCHAR(50) NOT NULL,
  `image` BLOB(8388000) NOT NULL,
  `mimetype` VARCHAR(45) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `creationUser` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`, `creationUser`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Image_Users1_idx` (`creationUser` ASC),
  CONSTRAINT `fk_Image_Users1`
    FOREIGN KEY (`creationUser`)
    REFERENCES `trueque-libre`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trueque-libre`.`ImagePublication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trueque-libre`.`ImagePublication` (
  `id` VARCHAR(50) NOT NULL,
  `idPublication` VARCHAR(50) NOT NULL,
  `idUser` VARCHAR(50) NOT NULL,
  `idImage` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`, `idPublication`, `idUser`, `idImage`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_ImagePublication_Publications1_idx` (`idPublication` ASC, `idUser` ASC),
  INDEX `fk_ImagePublication_Image1_idx` (`idImage` ASC),
  CONSTRAINT `fk_ImagePublication_Publications1`
    FOREIGN KEY (`idPublication` , `idUser`)
    REFERENCES `trueque-libre`.`Publications` (`id` , `creationUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ImagePublication_Image1`
    FOREIGN KEY (`idImage`)
    REFERENCES `trueque-libre`.`Image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trueque-libre`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trueque-libre`.`Chat` (
  `id` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NULL,
  `creationDate` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trueque-libre`.`Offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trueque-libre`.`Offers` (
  `id` VARCHAR(50) NOT NULL,
  `chatId` VARCHAR(50) NOT NULL,
  `imageId` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NULL,
  `state` VARCHAR(50) NULL,
  `creationDate` DATETIME NULL,
  `creationUser` VARCHAR(50) NOT NULL,
  `modificationDate` DATETIME NULL,
  `modificationUser` VARCHAR(150) NULL,
  PRIMARY KEY (`id`, `chatId`, `imageId`, `creationUser`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Offers_Users1_idx` (`creationUser` ASC),
  INDEX `fk_Offers_Chat1_idx` (`chatId` ASC),
  INDEX `fk_Offers_Image1_idx` (`imageId` ASC),
  CONSTRAINT `fk_Offers_Users1`
    FOREIGN KEY (`creationUser`)
    REFERENCES `trueque-libre`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offers_Chat1`
    FOREIGN KEY (`chatId`)
    REFERENCES `trueque-libre`.`Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offers_Image1`
    FOREIGN KEY (`imageId`)
    REFERENCES `trueque-libre`.`Image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trueque-libre`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trueque-libre`.`Tags` (
  `id` VARCHAR(50) NOT NULL,
  `tagName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `tagName_UNIQUE` (`tagName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trueque-libre`.`TagPublication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trueque-libre`.`TagPublication` (
  `idTags` VARCHAR(50) NOT NULL,
  `Publications_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTags`, `Publications_id`),
  INDEX `fk_TagPublication_Publications1_idx` (`Publications_id` ASC),
  CONSTRAINT `fk_TagPublication_Tags1`
    FOREIGN KEY (`idTags`)
    REFERENCES `trueque-libre`.`Tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TagPublication_Publications1`
    FOREIGN KEY (`Publications_id`)
    REFERENCES `trueque-libre`.`Publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
